{"name": "新建联系人失败-关联客户id不存在", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\nrun.py:121: AssumptionFailure\n>>\tpytest.assume(actual_res == expect_res, f'期望是{expect_res},实际是{actual_res}')\nAssertionError: 期望是500,实际是0\nassert False\n\nrun.py:121: AssumptionFailure\n>>\tpytest.assume(actual_res == expect_res, f'期望是{expect_res},实际是{actual_res}')\nAssertionError: 期望是服务器响应异常,实际是False\nassert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               run.py:121: AssumptionFailure\nE               >>\tpytest.assume(actual_res == expect_res, f'期望是{expect_res},实际是{actual_res}')\nE               AssertionError: 期望是500,实际是0\nE               assert False\nE               \nE               run.py:121: AssumptionFailure\nE               >>\tpytest.assume(actual_res == expect_res, f'期望是{expect_res},实际是{actual_res}')\nE               AssertionError: 期望是服务器响应异常,实际是False\nE               assert False\n\nC:\\Python37\\lib\\site-packages\\six.py:702: FailedAssumption"}, "attachments": [{"name": "log", "source": "bdc2c67f-3707-4e61-8d9a-f643d2681279-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "suite_name", "value": "'新建联系人接口测试集合'"}, {"name": "case_name", "value": "'新建联系人失败-关联客户id不存在'"}, {"name": "case_info_list", "value": "[['新建联系人', '${host}/CrmContacts/addOrUpdate', 'post', '{\\n\"Admin-Token\":\"${token}\"\\n}', '{\\n\"json\":{\\n\"$.entity.customer_id\":999999999,\\n}\\n}', '', 200, '[\\n{\\n\"actual\":\"$.code\",\\n\"expect\":500,\\n},\\n\\n{\\n\"actual\":\"$.msg\",\\n\"expect\":\"服务器响应异常\",\\n}\\n]']]"}], "start": 1661766075563, "stop": 1661766076177, "uuid": "4e774938-3eb7-46df-96c3-b3f65ca230e3", "historyId": "87c2c42d85ccaee53fb4a129e14d799c", "testCaseId": "581fcf0b30a85e3d611d5f9973144474", "fullName": "run#test_run", "labels": [{"name": "feature", "value": "新建联系人接口测试集合"}, {"name": "suite", "value": "run"}, {"name": "host", "value": "N-5CG8250K26"}, {"name": "thread", "value": "19024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "run"}]}